[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
simple_redis = "0.6.1"
uuid = { version = "1.1.2", features = ["v4"]}
diesel = { version = "1.4.8", features = ["postgres"] }
rocket = { version = "0.5.0-rc.2", features = ["json"] }
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.83"
rocket_cors = { git = "https://github.com/lawliet89/rocket_cors", branch = "master" }